args <- commandArgs(trailingOnly = TRUE)
library(GENIE3)
exprMatr <- read.table(args[1],sep='\t',header=1,row.names=1)
exprMatr<-as.matrix(exprMatr)
regulators <- read.table(args[2])
regulators <- as.character(unlist(regulators))
weightMat <- GENIE3(exprMatr, regulators=regulators, treeMethod="RF", nCores=20, verbose=TRUE)
write.csv(weightMat,args[3],quote=F)
linkList <- getLinkList(weightMat, threshold=0.005)
write.csv(linkList,args[4],quote=F,row.names=FALSE)
